config/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views


app_name = 'news'
urlpatterns = [
    path('create/', views.post_create, name='create'),
    path('category/<str:category>/', views.post_by_category, name='post_by_category'),
    path('detail/<int:pk>', views.post_detail, name='detail')
]

news/models.py
from django.db import models
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    short_content = models.TextField()
    long_content = models.TextField()
    author = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    created_at = models.DateField(auto_now_add=True)

    def get_detail_url(self):
        return reverse('news:detail', args=[self.pk])

    # get detail url

news/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post


def home(request):
    posts = Post.objects.all().order_by('-created_at')
    ctx = {'posts': posts}
    return render(request, 'index.html', ctx)


def post_create(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        short_content = request.POST.get('short_content')
        long_content = request.POST.get('long_content')
        author = request.POST.get('author')
        category = request.POST.get('category')
        if title and short_content and long_content and author and category:
            Post.objects.create(
                title=title,
                short_content=short_content,
                long_content=long_content,
                author=author,
                category=category
            )
            return redirect('home')
    return render(request, 'news/add-news.html')


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    ctx = {'post': post}
    return render(request, 'news/detail.html', ctx)

def post_by_category(request, category):
    posts = Post.objects.filter(category=category)
    ctx = {'posts': posts, 'category': category}
    return render(request, 'news/news-by-category.html', ctx)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {# EXTERNAL CSS #}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    {# HEADER #}
    {% include 'includes/header.html' %}

    {# NAVBAR #}
    {% include 'includes/nav.html' %}

    {# MAIN CONTENT #}
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    {# FOOTER #}
    <footer>
        <p>&copy; 2024 Yangiliklar Sayti. Barcha huquqlar himoyalangan.</p>
    </footer>
</body>
</html>

templates/includes/header.html
<header>
    <h1>Yangiliklar Sayti</h1>
</header>

templates/includes/nav.html
<nav>
    <ul>
        <li><a href="{% url 'home' %}">Bosh Sahifa</a></li>
        <li><a href="{% url 'news:post_by_category' 'mahalliy' %}">Mahalliy </a></li>
        <li><a href="{% url 'news:post_by_category' 'jahon' %}">Jahon</a></li>
        <li><a href="{% url 'news:post_by_category' 'sport' %}">Sport</a></li>
        <li><a href="{% url 'news:post_by_category' 'texnologiya' %}">Texnologiya</a></li>
        <li><a href="{% url 'news:create' %}">Yangilik Qo'shish</a></li>
    </ul>
</nav>

templates/index.html
{% extends 'base.html' %}

{% block title %}Yangiliklar sayti{% endblock %}

{% block content %}
    {% for post in posts %}
        <div class="news-item">
            <h2>{{ post.title }}</h2>
            <p>{{ post.short_content }}</p>
            <a href="{{ post.get_detail_url }}" class="read-more">Batafsil</a>
        </div>
    {% empty %}
        <h2>Hozircha yangilik yo'q</h2>
    {% endfor %}
{% endblock %}

templates/news/add-news.html
{% extends 'base.html' %}

{% block title %}Yangilik qo'shish{% endblock %}

{% block content %}
    <h2>Yangilik Qo'shish</h2>
    <form class="news-form" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Sarlavha:</label>
            <input type="text" id="title" name="title" required>
        </div>
        <div class="form-group">
            <label for="author">Avtor:</label>
            <input type="text" id="author" name="author" required>
        </div>
        <div class="form-group">
            <label for="category">Kategoriya:</label>
            <select id="category" name="category" required>
                <option value="">Select</option>
                <option value="mahalliy">Mahalliy</option>
                <option value="jahon">Jahon</option>
                <option value="sport">Sport</option>
                <option value="texnologiya">Texnologiya</option>
            </select>
        </div>
        <div class="form-group">
            <label for="short_content">Qisqa tavsif:</label>
            <textarea id="short_content" name="short_content" required></textarea>
        </div>
        <div class="form-group">
            <label for="long_content">Keng tavsif:</label>
            <textarea id="long_content" name="long_content" required></textarea>
        </div>
        <button type="submit" class="submit-btn">Yangilik qo'shish</button>
    </form>
{% endblock %}

templates/news/detail.html
{% extends 'base.html' %}
{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <article class="news-detail">
        <h2>{{ post.title }}</h2>
        <p class="news-meta">Sana: {{ post.created_at }} | Author: {{ post.author }}</p>
        <div class="news-content">
            <p>{{ post.long_content }}</p>
        </div>
    </article>
{% endblock %}

templates/news/news-by-category.html
{% extends 'base.html' %}
{% block title %} {{ category }} Yangiliklar {% endblock %}

{% block content %}
    {% for post in posts %}
        <h2 id="category-title">{{ post.title }}</h2>
        <div id="news-list">
            <div class="news-item">
                <h3>{{ post.short_content }}</h3>
                <a href="{{ post.get_detail_url }}" class="read-more">Batafsil</a>
            </div>
        </div>
    {% empty %}
        <h1>No Post Yet!</h1>
    {% endfor %}
{% endblock %}